### ISSUE TITLE
全屏组件能否加一个属性控制点X按钮才退出?

### ISSUE THREAD

**Issue by tangfeibiao** [alitajs/ant-design-plus#48]
## Background(背景)

当前全屏模式下不能操作页面里面的内容, 点击任何地方即退出全屏模式

## Proposal(建议)

增加一个属性,控制全屏退出的方式, 点击关闭按钮才退出全屏, 否则一直全屏

## Additional context(附加上下文)

Add any other context or screenshots about the feature request here.(在此处添加有关功能请求的任何其他上下文或屏幕截图。)

**Comment by wangxingkang** [comment]
谢谢反馈

**Comment by wangxingkang** [comment]
给个可退出的 按钮 ，用参数控制 是否显示？

**Comment by wangxingkang** [comment]
@chj-damon 进度如何？

**Comment by wangxingkang** [comment]
考虑了下 整个自己去写比较合适，一般都是受控的，先关闭
