### ISSUE TITLE
全屏模式希望可以提供滚动页面的功能

### ISSUE THREAD

**Issue by tangfeibiao** [alitajs/ant-design-plus#49]
## Background(背景)

全屏模式下,貌似不能滚动页面?

## Proposal(建议)

希望支持全屏模式下的滚动功能

## Additional context(附加上下文)

Add any other context or screenshots about the feature request here.(在此处添加有关功能请求的任何其他上下文或屏幕截图。)

**Comment by wangxingkang** [comment]
欢迎PR
