### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wangxingkang** [alitajs/ant-design-plus#5]
# 1.x

- [x] 验证码倒计时组件(SendCode)
- [x] 自适应文本组件(FitText)
- [x] 全屏组件(FullScreen)
- [x] 操作按钮列表组件(ButtonList)
- [x] 错误隔离组件(ErrorBoundary)
- [x] 权限组件(Authorized)

# 2.x

- [ ] 使用dumi重构文档
- [ ] 头像上传裁剪组件(AvatarCrop)
- [ ] 图片预览组件(PreviewImage)
- [ ] 无限滚动组件(InfiniteScroller )

**Comment by xiaohuoni** [comment]
无限滚动要不要搞一个类，直接继承来用就好？触发方式和方法固定下来。

**Comment by chj-damon** [comment]
> 无限滚动要不要搞一个类，直接继承来用就好？触发方式和方法固定下来。（H5，PC应该是可以通用）

不当成组件？

**Comment by xiaohuoni** [comment]
也是组件

**Comment by wangxingkang** [comment]
AvatarCrop 可参考项目

* https://github.com/mosch/react-avatar-editor
* https://github.com/dai-siki/vue-image-crop-upload

**Comment by AntoninSorrento** [comment]
进度怎么样了

**Comment by wangxingkang** [comment]
@AntoninSorrento  可以考虑加 ，欢迎PR

**Comment by wangxingkang** [comment]
@AntoninSorrento https://github.com/alitajs/ant-design-plus/pull/64 已支持

**Comment by AntoninSorrento** [comment]
效率赞👍

**Comment by wangxingkang** [comment]
已经 改成 function component 了
