### ISSUE TITLE
设置图片为背景，做一些操作的场景，比如 在图片上打点，自动缩放图片显示等等

### ISSUE THREAD

**Issue by wangxingkang** [alitajs/ant-design-plus#51]
# 组件大概实现图：
![image](https://user-images.githubusercontent.com/14227679/69719608-d0b58d80-114b-11ea-892f-82cdbd025a00.png)

要求：片区域要自适应外部容器，进行等比例缩放，并上下左右居中

# 初步API

## props

* className
* style
* src // 图片地址

## 事件
* onInit: (图片信息，缩放比) => void
* onError: () => void 图片加载失败

**Comment by wangxingkang** [comment]
打点的场景 需要再封装一层

**Comment by wangxingkang** [comment]
https://github.com/mbrevda/react-image  初步打算 在这个组件的基础上进行扩展

**Comment by ycjcl868** [comment]
antd 有相关 issue：https://github.com/ant-design/ant-design/issues/13719
rc-image WIP：https://github.com/react-component/image

**Comment by wangxingkang** [comment]
好的 我关注一下
