### ISSUE TITLE
使用ScrollableBar组件报错。。。。

### ISSUE THREAD

**Issue by xu-Aurora** [alitajs/ant-design-plus#60]
<img width="1436" alt="截屏2020-06-11 上午10 10 11" src="https://user-images.githubusercontent.com/35291465/84337297-caf53600-abcb-11ea-80e5-8915328f277d.png">
组件还是正常使用的，就是报这个错，怎么解决？

**Comment by xu-Aurora** [comment]
<img width="874" alt="截屏2020-06-11 上午10 35 13" src="https://user-images.githubusercontent.com/35291465/84338673-44daee80-abcf-11ea-9e4a-a6fe42287f15.png">
还有一个ts报错，也不知道为什么，虽然不性影响使用，但在ts项目中就是报这个错

**Comment by wangxingkang** [comment]
我看一下

**Comment by xu-Aurora** [comment]
> 我看一下

看了嘛？怎么样了？

**Comment by wangxingkang** [comment]
@xu-Aurora 你用的 antd 是什么版本 不好意思 最近回家了一趟

**Comment by xu-Aurora** [comment]
> @xu-Aurora 你用的 antd 是什么版本，看你的报错 应该是 antd@4导致的 不好意思 最近回家了一趟

对的，我用的就是antd4，配合你的这个使用就报错，把你的这个组件注释了就不报错了

**Comment by wangxingkang** [comment]
antd 有兼容方案 或者 等我升级完成后再使用

**Comment by wangxingkang** [comment]
头像一样 哈哈
