### ISSUE TITLE
SendCode 点击重新发送后错误

### ISSUE THREAD

**Issue by AntoninSorrento** [alitajs/ant-design-plus#69]
## What happens(发生了什么)?
SendCode 点击重新发送后错误
A clear and concise description of what the bug is(对错误的清晰而简明的描述).
官方示例也有此问题
## Mini Showcase Repository(迷你展示库)
[问题复现链接](https://antd-plus.alitajs.com/components/data-entry/send-code) 第二个例子(自定义倒计时按钮) 点击 <点击>按钮后，等待15秒，等重新发送的字样出来，在此点击就会出现页面空白

**Comment by wangxingkang** [comment]
好的，谢谢反馈，我这排查一下
